### ISSUE TITLE
Replace icon

### ISSUE THREAD

**Issue by sunya9** [sunya9/beta#109]
thanks! https://github.com/sunya9/beta/commit/cce535097c8f522714625a2d0d97cfb04aeaa8c1#commitcomment-28165794

**Comment by evefavretto** [comment]
The PNG is correct. So, why the beta logo is appearing different on, say, Chrome on the Mac?
![captura de tela 2018-07-21 as 17 57 57](https://user-images.githubusercontent.com/9127739/43040011-a933da76-8d0f-11e8-8cff-23b89fd739e0.png)

**Comment by 33mhz** [comment]
Whoops, that's not the file used. It's using an SVG. https://github.com/sunya9/beta/blob/8b0a8571e3802789c7c3170f7ab3493ae5239ce4/assets/img/beta.svg

Why an SVG looks bad on your Chrome on Mac, I don't know.

**Comment by evefavretto** [comment]
That SVG seems to have a different font. I did the logo with Montserrat.

**Comment by 33mhz** [comment]
There is no style guide that says Montserrat should be the font used. XD

My Montserrat β (linux, U+03B2 GREEK SMALL LETTER BETA) doesn't look like yours, at least in the Greek script. Can you export just the β as an SVG? Or at least paste the character here so I can confirm I'm using the same?

**Comment by evefavretto** [comment]
It should be this character β. 
[beta beta.svg.zip](https://github.com/sunya9/beta/files/2219970/beta.beta.svg.zip)

**Comment by 33mhz** [comment]
That's the same character, at least.

Haha. Still a base64 encoded image embedded in an SVG file.

**Comment by 33mhz** [comment]
Montserrat is an open font: https://github.com/JulietaUla/Montserrat/tree/master/fonts/ttf. That font still has the same β that I've been using. The font has been updated over the years, so it's possible you have an old version, but that would be strange. You could send me the font, or figure out how to export a real SVG.

This is two different issues, for you:
1) funky display - can you confirm it looks this way on any other browser or platform?
2) not the font you want - get us the font or an SVG

**Comment by 33mhz** [comment]
![screenshot_2018-07-23 beta](https://user-images.githubusercontent.com/1181047/43091075-ce344d5a-8e6e-11e8-8825-76f0d631ddff.png) - latest Firefox, Linux
![screenshot from 2018-07-23 11-51-33](https://user-images.githubusercontent.com/1181047/43091079-d1486666-8e6e-11e8-8c65-f25e50061202.png) - latest Chromium, Linux

**Comment by 33mhz** [comment]
Your "BETA" text looks wrong, too. I don't think this is an issue with the SVG or font that Beta is using.

**Comment by evefavretto** [comment]
[beta beta beta.svg.zip](https://github.com/sunya9/beta/files/2220756/beta.beta.beta.svg.zip)
Well, as far as I can tell, it should be Montserrat regular, 550pt more or less, with a dropshadow and slightly moved up and to the right for optical alignment(see this thread for info) https://beta.pnut.io/@formfireglass/posts/90125

**Comment by 33mhz** [comment]
If you can't make an SVG from the font, we don't have a source to recreate the logo as an SVG.

**Comment by evefavretto** [comment]
The new SVG isn't any good either? Pixelmator can't export to SVG, so I have to export to PSD and use another program to export to SVG. Here, again:
[beta beta beta.svg.zip](https://github.com/sunya9/beta/files/2220817/beta.beta.beta.svg.zip)

**Comment by 33mhz** [comment]
No, all of these are the same.

**Comment by evefavretto** [comment]
Let's see if it's correct now. It's black, but you can edit that.
[beta.svg.zip](https://github.com/sunya9/beta/files/2220855/beta.svg.zip)

**Comment by 33mhz** [comment]
OK. This works:
[revised_beta.svg.zip](https://github.com/sunya9/beta/files/2220991/revised_beta.svg.zip)

**Comment by evefavretto** [comment]
Way better.
