### ISSUE TITLE
Display and vote on polls

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#115]
https://pnut.io/docs/api/resources/polls

Posts and messages with `io.pnut.core.poll-notice` raw item has a poll. If the `closed_at` is in the future, you can still respond to it. Will have to GET the poll to know if the user has responded to it yet. Some sort of view of the poll on the post and then a button to pull up the details is probably reasonable.

Creating polls requires putting a replacement value in the raw on a new post:

https://github.com/pnut-api/object-metadata/blob/master/raw-replacement-values/%2Bio.pnut.core.poll.md

**Comment by sunya9** [comment]
Implemented on 563954277d3924c3d5c5639ae29af038a3c2ff6e
