### ISSUE TITLE
3 or more attached pictures in a post

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#116]
https://beta.pnut.io/@hybotics/posts/312557

Multiple pictures can interfere with text, and break the box layout for posts at medium widths.

**Comment by sunya9** [comment]
Oh
![screenshot from 2018-03-26 17-56-11](https://user-images.githubusercontent.com/451181/37896581-12f3d0f8-311f-11e8-9fa1-f7b43b89f28e.png)
