### ISSUE TITLE
Recalculate post length when deleting characters in markdown link

### ISSUE THREAD

**Issue by Lechindianer** [sunya9/beta#120]
I tried to post the following text:

`[Use your camera to light-paint your own platforms, freeze objects in place and solve challenging free form puzzles, in search of your missing friend! From Light is a 2D puzzle platformer in the same vein as The Swapper, Braid, and Fez, brightening up the genre with innovative photography inspired mechanics.](https://www.fig.co/campaigns/from-light)`

The UI showed me that the post is too long, so I wanted to shorten it to:

`[Use your camera to light-paint your own platforms, freeze objects in place and solve challenging free form puzzles, in search of your missing friend! From Light is a 2D puzzle platformer [...], brightening up the genre with innovative photography inspired mechanics.](https://www.fig.co/campaigns/from-light)`

The input field reported that I could still enter 65 more characters which is clearly wrong.

**Comment by 33mhz** [comment]
The regex `text.replace(/\[([^\]]+)\][^)]+\)/g, '$1')` is confused by the pair of brackets within brackets.

This seems to resolve properly: `text.replace(/\[(.+)\]\(((?:https?:\/\/)?([^/?#]+)[^\)]*)\)/g, '$1 [$3]')`, but I don't know how much cost difference there is. On Firefox, Linux, typing is significantly slowed by whatever checks are happening on every keystroke as it is.

**Comment by 33mhz** [comment]
I think I was mistaken. This would be better:
`text.replace(/\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?((?:\([^)]*\)|[^()\s])*?)>?([ \t]*)((['"])(.*?)\6[ \t]*)?\)/g, '[$2]')`
That's what Broadsword uses, and it doesn't have any issue with performance.

Anecdotally, Beta is very slow in Firefox typing, and it's OK but not great in Chrome.
