### ISSUE TITLE
Orient images correctly based on metadata

### ISSUE THREAD

**Issue by sevan** [sunya9/beta#125]
If a photo is taken with the camera upside down, re-orient the image the right way up based on the metadata rather than showing image upside down in posts.

**Comment by jeremycherfas** [comment]
This is definitely still an issue with the way Beta displays images. See, for example, https://beta.pnut.io/@jeremycherfas/posts/372113

**Comment by 33mhz** [comment]
Hopefully this will be implemented: https://github.com/pnut-api/api-spec/issues/63

**Comment by sevan** [comment]
Tested with firefox, issue appears to be fixed. Thank you!
