### ISSUE TITLE
Add keyboard shortcut to messages

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#151]

**Comment by sunya9** [comment]
What kind of shortcut keys are necessary? for example, when pressed `n` on the `/messages`, show a modal to create a private message?

**Comment by 33mhz** [comment]
It would be nice to have a shortcut to navigate to `/messages`.

Another feature that I would find handy would be the ability to pull up the New Private Message as a modal like the New Post modal, from anywhere.

**Comment by sunya9** [comment]
Fixed on a80ffa7c0a24a268c84b085a97dd64f68d1bcc39
