### ISSUE TITLE
Add indicator for unread messages

### ISSUE THREAD

**Issue by hutattedonmyarm** [sunya9/beta#168]
Currently I have to click on the envelope to check if I have any unread messages. A small indicator (color it red, add a red dot, whatever) on the icon itself would be helpful

**Comment by 33mhz** [comment]
This is definitely a missing piece, and will probably be simple to implement once #163 is done.

**Comment by 33mhz** [comment]
It looks like this was completed!

**Comment by sunya9** [comment]
:laughing:
