### ISSUE TITLE
Hangs after logging in

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#220]
**Describe the bug**
When logging in for the first time, it hangs after retrieving an access code, at https://beta.pnut.io/callback?XXXX#access_code=XXXXX. Refreshing the page loads the site again as the logged-in user, properly.

**To Reproduce**
1. log in
2. after redirecting to Pnut.io, it redirects back to beta
3. hangs

**Comment by sunya9** [comment]
Is it occur always? I tried to reproduce, But not so often encountered.

**Comment by 33mhz** [comment]
It isn't happening now - but when I initially go to beta.pnut.io, after closing the browser, it always acts as if I'm not signed in, until I refresh the view. Others have this problem, too.
