### ISSUE TITLE
Rendering links in posts

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#3]
Sometimes breaks: https://beta.unsweets.net/posts/78139

**Comment by 33mhz** [comment]
Links also try to open in the web page.
https://beta.unsweets.net/posts/78168

The link should be https://github.com/bazbt3/pnut_io_stuff/wiki/WednesdayChallenge, but it tries to open https://beta.unsweets.net/bazbt3/pnut_io_stuff/wiki/WednesdayChallenge

**Comment by sunya9** [comment]
Fixed.
