### ISSUE TITLE
audio and photos views

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#349]
**Is your feature request related to a problem? Please describe.**
Like the poll-specific views (`/polls/{id}`), it would be good to have a view of audio- and photo-type files.

**Describe the solution you'd like**
Pnut.io can have audio.pnut.io/{file_id} and photos.pnut.io/{file_id} subdomains, and point them at Beta. Beta would look up the files, and if they are of an appropriate `kind`, display them on the page.

It could help to have those views also at beta.pnut.io/audio/{file_id} and beta.pnut.io/photos/{file_id}.

**Comment by sunya9** [comment]
I implemented a similar feature a while ago. It can view a file by visiting to `/files/{id}`. What do you think?

**Comment by 33mhz** [comment]
Yes, that'll work! I didn't realize. Pnut can redirect the file types there, then.
