### ISSUE TITLE
Specific markdown links result in an error 

### ISSUE THREAD

**Issue by Lechindianer** [sunya9/beta#45]
If I want to send a Markdown link in Beta with link "sea-shepherd.de" I'll get a 400 from "beta.unsweets.net/proxy/posts".

It works when I use "www.sea-shepherd.de" instead

![Error in console](https://image.ibb.co/m1rptw/2017_10_07_205613_3200x1200_scrot.png)

I'm running Beta version 1.6.2 on Chrome

**Comment by 33mhz** [comment]
This appears to have worked itself out. Posting `[testing a link](sea-shepherd.de)` worked: https://beta.unsweets.net/@33MHz/posts/217629. Let me know if there are other cases.

**Comment by Lechindianer** [comment]
fixed
