### ISSUE TITLE
emoji palette too slow

### ISSUE THREAD

**Issue by sunya9** [sunya9/beta#48]

**Comment by 33mhz** [comment]
![screenshot from 2018-08-01 22-16-48](https://user-images.githubusercontent.com/1181047/43560559-afd0dd12-95d8-11e8-95c2-b2e5d7cac469.png)
Yeah, typing with that on the page is painful.

**Comment by 33mhz** [comment]
This is an alternative that seems fast, but looks like it doesn't render emoji for users - it's just native emoji.

https://github.com/DCzajkowski/vue-emoji-picker
