### ISSUE TITLE
Browser mention notifications

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#5]
On mobile, particularly, this would be great.

**Comment by 33mhz** [comment]
Would be nice to have a mention counter at the top indicating that someone mentioned you, going in the background, as well. Maybe this is what you have in mind for App Streams.

**Comment by sunya9** [comment]
Implemented in https://github.com/sunya9/beta/commit/c5f1ce7e041c3c480190352d2c7e72a140d30fc3
