### ISSUE TITLE
Cancel button for composing a post

### ISSUE THREAD

**Issue by schmidt-fu** [sunya9/beta#7]
Sometimes I start writing a post in the "My stream" view, but don't finish and send it. When I continue browsing, I find it irritating that the unfinished text stays in the textbox.
I'd rather tap/click a "Cancel" button next to the "Post" one that simply deletes the unfinished post.

**Comment by sunya9** [comment]
Sorry for my late reply. In the current version, compose text is reset by transition page.
If put the cancel button, I think that need to show the confirm dialog too. That is the mean that two modal dialogs are shown. I think complexity in the point of the implement and user interface. So, I think that the better not have to put the cancel button.

**Comment by odilitime** [comment]
save the current message somewhere (cookie)? and then no need for confirmation. Auto populate the storage message if dialog is opened again.

**Comment by 33mhz** [comment]
Does someone still want something done, or should this be closed?

**Comment by 33mhz** [comment]
I think this can be closed.
