### ISSUE TITLE
Update for bootstrap 4.0.0

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#73]
https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.2

at least
* checkboxes

**Comment by 33mhz** [comment]
I think some things may break between beta2 and beta3 of bootstrap 4. E.g., checkboxes changed between 2 and 3: https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.3

I'm not sure about anything else. When I tried updating to 4.0.0 release, I knew the checkboxes broke and backed off.

**Comment by sunya9** [comment]
I fixed this problem and it has upgraded!
