### ISSUE TITLE
Do not show image upload for users who can't upload

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#75]
File upload requires a pnut badge. Either show a notice explaining what they need, or don't show the feature at all. Might be nice to add an option in Settings, where a user can see that beta doesn't know they have a badge, and allow them to refresh their token, so beta can see they have a badge, and enable the feature.

**Comment by 33mhz** [comment]
It might be reasonable to [GET a user's token](https://pnut.io/docs/api/resources/token#get-token) every time they open the app, to double-check authorized scopes from the `X-OAuth-Scopes` header and read how much file storage they have.

**Comment by 33mhz** [comment]
OH - this is handled?

**Comment by sunya9** [comment]
Sorry, upload button had shown in previous version. But currently version alreday fixed.
