### ISSUE TITLE
Unclear meaning of the conversation symbol

### ISSUE THREAD

**Issue by schmidt-fu** [sunya9/beta#8]
There's a symbol below a post's text that indicates if there's more than one post in the conversation.
I expect it to take me to a different view than either the post creation time (left of it) or the text "Reply...". However it opens a view that immediately opens a keyboard on mobile, hiding most of the conversation I want to see in the first place.
Suggestion: Hide the textbox for replying when this symbol is clicked, or separate it from the other symbol so it dosn't look actionable.

**Comment by sunya9** [comment]
I implemented reply with modal dialog.  How is that?

**Comment by schmidt-fu** [comment]
Great improvement, it works much better for me!

It has never failed to send a post, but how do you think about displaying a confirmation that a post has been sent? Most clients show some non-modal overlay for a short while.

**Comment by schmidt-fu** [comment]
I moved the discussion of post confirmation in #18 as a separate issue, so this can be closed.
Thank you for implementing!
