### ISSUE TITLE
Smart multi reply

### ISSUE THREAD

**Issue by sunya9** [sunya9/beta#98]
Currently, The are two buttons Reply and Reply All in the post component.
But Those occupy spaces. So, I would like to put only Reply button.

When clicked reply, it becomes to selected state that the texts of another user.

![screenshot from 2018-03-18 13-41-43](https://user-images.githubusercontent.com/451181/37562690-1c7ce89e-2ab2-11e8-8a69-7f868a8f5cbe.png)

**Comment by 33mhz** [comment]
Sounds convenient. I'm for it. Alternatively, could make "Reply" and "Reply All" text disappear, and leave the reply icons with narrow screen widths. But "Smart" reply is good.
